`include "param.vh"

module PT_CE #(
	parameter DATA_WIDTH   = 32,
	parameter GEMM_X_DIM   = 4,
	parameter GEMM_Y_DIM   = 4,
	parameter A_BANK_DEPTH = 16,
	parameter B_BANK_DEPTH = 16,
	parameter M_BANK_DEPTH = 16,
	parameter M_WRITE_LANES = GEMM_Y_DIM
) (
	input  wire                       clk,
	input  wire                       rstn,
	input  wire                       clear,
	input  wire                       ce_cmd_valid,
	output wire                       ce_cmd_ready,
	input  wire [`INST_WIDTH-1:0]     ce_cmd_ctrl,
	input  wire [31:0]                ce_cmd_id,
	input  wire [`PT_LOCAL_ADDR_W-1:0] ce_a_local_base,
	input  wire [`PT_LOCAL_ADDR_W-1:0] ce_b_local_base,
	input  wire                       ce_m_wr_buf,
	output wire                       a_mem_rd_en,
	output wire                       exec_a_buf,
	output wire [(((A_BANK_DEPTH * GEMM_X_DIM) <= 1) ? 1 : $clog2(A_BANK_DEPTH * GEMM_X_DIM))-1:0] exec_a_addr,
	output wire                       b_mem_rd_en,
	output wire                       exec_b_buf,
	output wire [(((B_BANK_DEPTH * GEMM_Y_DIM) <= 1) ? 1 : $clog2(B_BANK_DEPTH * GEMM_Y_DIM))-1:0] exec_b_addr,
	output wire                       exec_m_b_buf,
	output wire [(((M_BANK_DEPTH * GEMM_X_DIM) <= 1) ? 1 : $clog2(M_BANK_DEPTH * GEMM_X_DIM))-1:0] exec_m_b_addr,
	output wire                       exec_m_b_rd_en,
	output wire                       gemm_a_valid,
	output wire                       gemm_b_valid,
	output wire                       gemm_start,
	output wire [DATA_WIDTH-1:0]      gemm_num_acc,
	input  wire                       gemm_a_ready,
	input  wire                       gemm_b_ready,
	input  wire                       gemm_start_ready,
	input  wire [GEMM_Y_DIM*DATA_WIDTH-1:0] quant_m_data,
	input  wire [31:0]                quant_m_idx,
	input  wire                       quant_m_valid,
	input  wire                       quant_m_last,
	output wire                       quant_m_ready,
	input  wire [GEMM_Y_DIM*DATA_WIDTH-1:0] b_mem_row_data,
	input  wire [GEMM_Y_DIM*DATA_WIDTH-1:0] m_mem_row_data,
	input  wire                       m_buf0_single_output,
	input  wire                       m_buf1_single_output,
	output wire [GEMM_Y_DIM*DATA_WIDTH-1:0] gema_lhs_data,
	output wire [GEMM_Y_DIM*DATA_WIDTH-1:0] gema_rhs_data,
	output wire [31:0]                gema_in_idx,
	output wire                       gema_in_last,
	output wire                       gema_in_valid,
	input  wire                       gema_in_ready,
	input  wire [GEMM_Y_DIM*DATA_WIDTH-1:0] add_m_data,
	input  wire [31:0]                add_m_idx,
	input  wire                       add_m_valid,
	input  wire                       add_m_last,
	output wire                       add_m_ready,
	output wire                       m_mem_wr_en,
	output wire                       m_mem_wr_buf,
	output wire [GEMM_Y_DIM-1:0]      m_mem_wr_mask,
	output wire [(((M_BANK_DEPTH * GEMM_X_DIM) <= 1) ? 1 : $clog2(M_BANK_DEPTH * GEMM_X_DIM))-1:0] m_mem_wr_addr,
	output wire [GEMM_Y_DIM*DATA_WIDTH-1:0]      m_mem_wr_data,
	output wire                       ce_resp_valid,
	output wire [31:0]                ce_resp,
	output wire [`PT_SIZE_W-1:0]      ce_resp_row_chunk_count,
	output wire                       ce_resp_single_output,
	output wire                       ce_irq
);

	PT_CE_V2 #(
		.DATA_WIDTH  (DATA_WIDTH),
		.GEMM_X_DIM  (GEMM_X_DIM),
		.GEMM_Y_DIM  (GEMM_Y_DIM),
		.A_BANK_DEPTH(A_BANK_DEPTH),
		.B_BANK_DEPTH(B_BANK_DEPTH),
		.M_BANK_DEPTH(M_BANK_DEPTH),
		.M_WRITE_LANES(M_WRITE_LANES)
	) u_ce_v2 (
		.clk            (clk),
		.rstn           (rstn),
		.clear          (clear),
		.ce_cmd_valid   (ce_cmd_valid),
		.ce_cmd_ready   (ce_cmd_ready),
		.ce_cmd_ctrl    (ce_cmd_ctrl),
		.ce_cmd_id      (ce_cmd_id),
		.ce_a_local_base(ce_a_local_base),
		.ce_b_local_base(ce_b_local_base),
		.ce_m_wr_buf    (ce_m_wr_buf),
		.a_mem_rd_en    (a_mem_rd_en),
		.exec_a_buf     (exec_a_buf),
		.exec_a_addr    (exec_a_addr),
		.b_mem_rd_en    (b_mem_rd_en),
		.exec_b_buf     (exec_b_buf),
		.exec_b_addr    (exec_b_addr),
		.exec_m_b_buf   (exec_m_b_buf),
		.exec_m_b_addr  (exec_m_b_addr),
		.exec_m_b_rd_en (exec_m_b_rd_en),
		.gemm_a_valid   (gemm_a_valid),
		.gemm_b_valid   (gemm_b_valid),
		.gemm_start     (gemm_start),
		.gemm_num_acc   (gemm_num_acc),
		.gemm_a_ready   (gemm_a_ready),
		.gemm_b_ready   (gemm_b_ready),
		.gemm_start_ready(gemm_start_ready),
		.quant_m_data   (quant_m_data),
		.quant_m_idx    (quant_m_idx),
		.quant_m_valid  (quant_m_valid),
		.quant_m_last   (quant_m_last),
		.quant_m_ready  (quant_m_ready),
		.b_mem_row_data (b_mem_row_data),
		.m_mem_row_data (m_mem_row_data),
		.m_buf0_single_output(m_buf0_single_output),
		.m_buf1_single_output(m_buf1_single_output),
		.gema_lhs_data  (gema_lhs_data),
		.gema_rhs_data  (gema_rhs_data),
		.gema_in_idx    (gema_in_idx),
		.gema_in_last   (gema_in_last),
		.gema_in_valid  (gema_in_valid),
		.gema_in_ready  (gema_in_ready),
		.add_m_data     (add_m_data),
		.add_m_idx      (add_m_idx),
		.add_m_valid    (add_m_valid),
		.add_m_last     (add_m_last),
		.add_m_ready    (add_m_ready),
		.m_mem_wr_en    (m_mem_wr_en),
		.m_mem_wr_buf   (m_mem_wr_buf),
		.m_mem_wr_mask  (m_mem_wr_mask),
		.m_mem_wr_addr  (m_mem_wr_addr),
		.m_mem_wr_data  (m_mem_wr_data),
		.ce_resp_valid  (ce_resp_valid),
		.ce_resp        (ce_resp),
		.ce_resp_row_chunk_count(ce_resp_row_chunk_count),
		.ce_resp_single_output(ce_resp_single_output),
		.ce_irq         (ce_irq)
	);

endmodule
