`include "param.vh"

module PT_MD #(
	parameter DATA_WIDTH   = 32,
	parameter GEMM_X_DIM   = 4,
	parameter GEMM_Y_DIM   = 4,
	parameter DMA_BEATS_W  = 16,
	parameter A_BANK_DEPTH = 8,
	parameter B_BANK_DEPTH = 16,
	parameter M_BANK_DEPTH = 16,
	parameter A_LOAD_LANES = GEMM_X_DIM,
	parameter B_LOAD_LANES = GEMM_Y_DIM,
	parameter M_EXPORT_LANES = GEMM_Y_DIM
) (
	input  wire                       clk,
	input  wire                       rstn,
	input  wire                       clear,
	input  wire                       md_cmd_valid,
	output wire                       md_cmd_ready,
	input  wire [`PT_MEM_KIND_W-1:0]  md_cmd_kind,
	input  wire [`INST_WIDTH-1:0]     md_cmd_inst,
	input  wire [31:0]                md_cmd_id,
	output wire                       md_cmd_resp_valid,
	output wire [31:0]                md_cmd_resp,
	output wire                       md_cmd_irq,
	output wire                       md_async_resp_valid,
	output wire [31:0]                md_async_resp,
	output wire                       md_async_irq,
	input  wire                       fill_req_valid,
	output wire                       fill_req_ready,
	input  wire [`PT_DMA_KIND_W-1:0]  fill_req_kind,
	input  wire [31:0]                fill_req_id,
	input  wire [`PT_LOCAL_ADDR_W-1:0] fill_req_local_base,
	input  wire [`PT_SIZE_W-1:0]      fill_req_len,
	output wire                       fill_done_valid,
	output wire [`PT_DMA_KIND_W-1:0]  fill_done_kind,
	output wire [31:0]                fill_done_id,
	output wire                       fill_done_err,
	input  wire                       s_axis_tvalid,
	input  wire [(((A_LOAD_LANES >= B_LOAD_LANES) ? A_LOAD_LANES : B_LOAD_LANES)*DATA_WIDTH)-1:0]      s_axis_tdata,
	input  wire [1:0]                 s_axis_tuser,
	output wire                       s_axis_tready,
	output wire                       dma_req_valid,
	input  wire                       dma_req_ready,
	output wire [`PT_DMA_KIND_W-1:0]  dma_req_kind,
	output wire [31:0]                dma_req_id,
	input  wire                       dma_error,
	output wire                       a_mem_wr_en,
	output wire                       a_mem_wr_buf,
	output wire [GEMM_X_DIM-1:0]      a_mem_wr_mask,
	output wire [(((A_BANK_DEPTH * GEMM_X_DIM) <= 1) ? 1 : $clog2(A_BANK_DEPTH * GEMM_X_DIM))-1:0] a_mem_wr_addr,
	output wire [GEMM_X_DIM*DATA_WIDTH-1:0]      a_mem_wr_data,
	output wire                       b_mem_wr_en,
	output wire                       b_mem_wr_buf,
	output wire [GEMM_Y_DIM-1:0]      b_mem_wr_mask,
	output wire [(((B_BANK_DEPTH * GEMM_Y_DIM) <= 1) ? 1 : $clog2(B_BANK_DEPTH * GEMM_Y_DIM))-1:0] b_mem_wr_addr,
	output wire [GEMM_Y_DIM*DATA_WIDTH-1:0]      b_mem_wr_data,
	input  wire                       m_alloc_take,
	output wire                       m_alloc_ready,
	output wire                       m_alloc_buf,
	input  wire                       ce_resp_valid,
	input  wire [31:0]                ce_resp,
	output wire                       m_dma_req_valid,
	input  wire                       m_dma_req_ready,
	output wire [31:0]                m_dma_req_id,
	output wire                       m_dma_req_buf,
	output wire [DMA_BEATS_W-1:0]     m_dma_req_beats,
	input  wire                       m_dma_done,
	input  wire                       m_dma_error,
	output wire                       m_axis_tvalid,
	input  wire                       m_axis_tready,
	output wire [M_EXPORT_LANES*DATA_WIDTH-1:0]      m_axis_tdata,
	output wire [M_EXPORT_LANES*DATA_WIDTH/8-1:0]    m_axis_tstrb,
	output wire                       m_axis_tlast,
	output wire                       m_axis_tkeep,
	output wire                       m_axis_tid,
	output wire                       m_axis_tdest,
	output wire [1:0]                 m_axis_tuser,
	output wire                       exp_rd_en,
	output wire                       exp_rd_buf,
	output wire [(((M_BANK_DEPTH * GEMM_X_DIM) <= 1) ? 1 : $clog2(M_BANK_DEPTH * GEMM_X_DIM))-1:0] exp_rd_addr,
	input  wire [GEMM_Y_DIM*DATA_WIDTH-1:0] exp_rd_data,
	input  wire [((GEMM_X_DIM >= GEMM_Y_DIM) ? GEMM_X_DIM : GEMM_Y_DIM)*32-1:0] csr_quant_inv_scale,
	output wire                       csr_a_base_lo_we,
	output wire                       csr_a_base_hi_we,
	output wire                       csr_b_base_lo_we,
	output wire                       csr_b_base_hi_we,
	output wire [15:0]                csr_cfg_wdata16,
	output wire                       csr_quant_commit_we,
	output wire [2:0]                 csr_quant_mode_wdata,
	output wire [((GEMM_X_DIM >= GEMM_Y_DIM) ? GEMM_X_DIM : GEMM_Y_DIM)*32-1:0] csr_quant_inv_scale_wdata
);

	PT_MD_V2 #(
		.DATA_WIDTH  (DATA_WIDTH),
		.GEMM_X_DIM  (GEMM_X_DIM),
		.GEMM_Y_DIM  (GEMM_Y_DIM),
		.DMA_BEATS_W (DMA_BEATS_W),
		.A_BANK_DEPTH(A_BANK_DEPTH),
		.B_BANK_DEPTH(B_BANK_DEPTH),
		.M_BANK_DEPTH(M_BANK_DEPTH),
		.A_LOAD_LANES(A_LOAD_LANES),
		.B_LOAD_LANES(B_LOAD_LANES),
		.M_EXPORT_LANES(M_EXPORT_LANES)
	) u_md_v2 (
		.clk                 (clk),
		.rstn                (rstn),
		.clear               (clear),
		.md_cmd_valid        (md_cmd_valid),
		.md_cmd_ready        (md_cmd_ready),
		.md_cmd_kind         (md_cmd_kind),
		.md_cmd_inst         (md_cmd_inst),
		.md_cmd_id           (md_cmd_id),
		.md_cmd_resp_valid   (md_cmd_resp_valid),
		.md_cmd_resp         (md_cmd_resp),
		.md_cmd_irq          (md_cmd_irq),
		.md_async_resp_valid (md_async_resp_valid),
		.md_async_resp       (md_async_resp),
		.md_async_irq        (md_async_irq),
		.fill_req_valid      (fill_req_valid),
		.fill_req_ready      (fill_req_ready),
		.fill_req_kind       (fill_req_kind),
		.fill_req_id         (fill_req_id),
		.fill_req_local_base (fill_req_local_base),
		.fill_req_len        (fill_req_len),
		.fill_done_valid     (fill_done_valid),
		.fill_done_kind      (fill_done_kind),
		.fill_done_id        (fill_done_id),
		.fill_done_err       (fill_done_err),
		.s_axis_tvalid       (s_axis_tvalid),
		.s_axis_tdata        (s_axis_tdata),
		.s_axis_tuser        (s_axis_tuser),
		.s_axis_tready       (s_axis_tready),
		.dma_req_valid       (dma_req_valid),
		.dma_req_ready       (dma_req_ready),
		.dma_req_kind        (dma_req_kind),
		.dma_req_id          (dma_req_id),
		.dma_error           (dma_error),
		.a_mem_wr_en         (a_mem_wr_en),
		.a_mem_wr_buf        (a_mem_wr_buf),
		.a_mem_wr_mask       (a_mem_wr_mask),
		.a_mem_wr_addr       (a_mem_wr_addr),
		.a_mem_wr_data       (a_mem_wr_data),
		.b_mem_wr_en         (b_mem_wr_en),
		.b_mem_wr_buf        (b_mem_wr_buf),
		.b_mem_wr_mask       (b_mem_wr_mask),
		.b_mem_wr_addr       (b_mem_wr_addr),
		.b_mem_wr_data       (b_mem_wr_data),
		.m_alloc_take        (m_alloc_take),
		.m_alloc_ready       (m_alloc_ready),
		.m_alloc_buf         (m_alloc_buf),
		.ce_resp_valid       (ce_resp_valid),
		.ce_resp             (ce_resp),
		.m_dma_req_valid     (m_dma_req_valid),
		.m_dma_req_ready     (m_dma_req_ready),
		.m_dma_req_id        (m_dma_req_id),
		.m_dma_req_buf       (m_dma_req_buf),
		.m_dma_req_beats     (m_dma_req_beats),
		.m_dma_done          (m_dma_done),
		.m_dma_error         (m_dma_error),
		.m_axis_tvalid       (m_axis_tvalid),
		.m_axis_tready       (m_axis_tready),
		.m_axis_tdata        (m_axis_tdata),
		.m_axis_tstrb        (m_axis_tstrb),
		.m_axis_tlast        (m_axis_tlast),
		.m_axis_tkeep        (m_axis_tkeep),
		.m_axis_tid          (m_axis_tid),
		.m_axis_tdest        (m_axis_tdest),
		.m_axis_tuser        (m_axis_tuser),
		.exp_rd_en           (exp_rd_en),
		.exp_rd_buf          (exp_rd_buf),
		.exp_rd_addr         (exp_rd_addr),
		.exp_rd_data         (exp_rd_data),
		.csr_quant_inv_scale (csr_quant_inv_scale),
		.csr_a_base_lo_we    (csr_a_base_lo_we),
		.csr_a_base_hi_we    (csr_a_base_hi_we),
		.csr_b_base_lo_we    (csr_b_base_lo_we),
		.csr_b_base_hi_we    (csr_b_base_hi_we),
		.csr_cfg_wdata16     (csr_cfg_wdata16),
		.csr_quant_commit_we (csr_quant_commit_we),
		.csr_quant_mode_wdata(csr_quant_mode_wdata),
		.csr_quant_inv_scale_wdata(csr_quant_inv_scale_wdata)
	);

endmodule
