`include "param.vh"

module PT_V3 #(
	parameter DATA_WIDTH   = 32,
	parameter WORD_WIDTH   = 32,
	parameter ELEM_WIDTH   = 8,
	parameter PACK_LANES   = 4,
	parameter ACC_WIDTH    = 32,
	parameter GEMM_X_DIM   = 4,
	parameter GEMM_Y_DIM   = 4,
	parameter EXT_ADDR_W   = 32,
	parameter DMA_BEATS_W  = 16,
	parameter LUT_DEPTH    = 8,
	parameter A_BANK_DEPTH = 16,
	parameter B_BANK_DEPTH = 16,
	parameter M_BANK_DEPTH = 16,
	parameter A_LOAD_LANES = GEMM_X_DIM,
	parameter B_LOAD_LANES = GEMM_Y_DIM,
	parameter M_WRITE_LANES = GEMM_Y_DIM,
	parameter M_EXPORT_LANES = GEMM_Y_DIM,
	parameter M_PHYSICAL_COPIES = 2
) (
	input  wire                       clk,
	input  wire                       rstn,
	input  wire                       clear,
	input  wire                       soft_clear,
	input  wire                       s_axis_tvalid,
	output wire                       s_axis_tready,
	input  wire [((A_LOAD_LANES >= B_LOAD_LANES) ? A_LOAD_LANES : B_LOAD_LANES)*DATA_WIDTH-1:0]      s_axis_tdata,
	input  wire [((A_LOAD_LANES >= B_LOAD_LANES) ? A_LOAD_LANES : B_LOAD_LANES)*DATA_WIDTH/8-1:0]    s_axis_tstrb,
	input  wire                       s_axis_tlast,
	input  wire                       s_axis_tkeep,
	input  wire                       s_axis_tid,
	input  wire                       s_axis_tdest,
	input  wire [1:0]                 s_axis_tuser,
	output wire                       m_axis_tvalid,
	input  wire                       m_axis_tready,
	output wire [M_EXPORT_LANES*DATA_WIDTH-1:0]      m_axis_tdata,
	output wire [M_EXPORT_LANES*DATA_WIDTH/8-1:0]    m_axis_tstrb,
	output wire                       m_axis_tlast,
	output wire                       m_axis_tkeep,
	output wire                       m_axis_tid,
	output wire                       m_axis_tdest,
	output wire [1:0]                 m_axis_tuser,
	input  wire                       ctrl_valid,
	output wire                       ctrl_ready,
	input  wire [`INST_WIDTH-1:0]     ctrl_inst,
	input  wire [31:0]                ctrl_id,
	output wire [31:0]                ctrl_resp,
	output wire                       ctrl_resp_valid,
	output wire                       dma_req_valid,
	input  wire                       dma_req_ready,
	output wire [`PT_DMA_KIND_W-1:0]  dma_req_kind,
	output wire [31:0]                dma_req_id,
	input  wire                       dma_done,
	input  wire                       dma_error,
	output wire                       m_dma_req_valid,
	input  wire                       m_dma_req_ready,
	output wire [31:0]                m_dma_req_id,
	output wire                       m_dma_req_buf,
	output wire [DMA_BEATS_W-1:0]     m_dma_req_beats,
	input  wire                       m_dma_done,
	input  wire                       m_dma_error,
	output wire                       irq
);

	localparam integer LOAD_STREAM_LANES = (A_LOAD_LANES >= B_LOAD_LANES) ? A_LOAD_LANES : B_LOAD_LANES;
	localparam integer LOAD_STREAM_STRB_W = LOAD_STREAM_LANES * DATA_WIDTH / 8;

	PT_TOP_V3 #(
		.DATA_WIDTH  (DATA_WIDTH),
		.WORD_WIDTH  (WORD_WIDTH),
		.ELEM_WIDTH  (ELEM_WIDTH),
		.PACK_LANES  (PACK_LANES),
		.ACC_WIDTH   (ACC_WIDTH),
		.GEMM_X_DIM  (GEMM_X_DIM),
		.GEMM_Y_DIM  (GEMM_Y_DIM),
		.EXT_ADDR_W  (EXT_ADDR_W),
		.DMA_BEATS_W (DMA_BEATS_W),
		.LUT_DEPTH   (LUT_DEPTH),
		.A_BANK_DEPTH(A_BANK_DEPTH),
		.B_BANK_DEPTH(B_BANK_DEPTH),
		.M_BANK_DEPTH(M_BANK_DEPTH),
		.A_LOAD_LANES(A_LOAD_LANES),
		.B_LOAD_LANES(B_LOAD_LANES),
		.M_WRITE_LANES(M_WRITE_LANES),
		.M_EXPORT_LANES(M_EXPORT_LANES),
		.M_PHYSICAL_COPIES(M_PHYSICAL_COPIES)
	) u_pt_v3 (
		.clk            (clk),
		.rstn           (rstn),
		.clear          (clear),
		.soft_clear     (soft_clear),
		.s_axis_tvalid  (s_axis_tvalid),
		.s_axis_tready  (s_axis_tready),
		.s_axis_tdata   (s_axis_tdata),
		.s_axis_tstrb   ({LOAD_STREAM_STRB_W{1'b0}}),
		.s_axis_tlast   (1'b0),
		.s_axis_tkeep   (1'b0),
		.s_axis_tid     (1'b0),
		.s_axis_tdest   (1'b0),
		.s_axis_tuser   (s_axis_tuser),
		.m_axis_tvalid  (m_axis_tvalid),
		.m_axis_tready  (m_axis_tready),
		.m_axis_tdata   (m_axis_tdata),
		.m_axis_tstrb   (m_axis_tstrb),
		.m_axis_tlast   (m_axis_tlast),
		.m_axis_tkeep   (m_axis_tkeep),
		.m_axis_tid     (m_axis_tid),
		.m_axis_tdest   (m_axis_tdest),
		.m_axis_tuser   (m_axis_tuser),
		.ctrl_valid     (ctrl_valid),
		.ctrl_ready     (ctrl_ready),
		.ctrl_inst      (ctrl_inst),
		.ctrl_id        (ctrl_id),
		.ctrl_resp      (ctrl_resp),
		.ctrl_resp_valid(ctrl_resp_valid),
		.dma_req_valid  (dma_req_valid),
		.dma_req_ready  (dma_req_ready),
		.dma_req_kind   (dma_req_kind),
		.dma_req_id     (dma_req_id),
		.dma_done       (1'b0),
		.dma_error      (dma_error),
		.m_dma_req_valid(m_dma_req_valid),
		.m_dma_req_ready(m_dma_req_ready),
		.m_dma_req_id   (m_dma_req_id),
		.m_dma_req_buf  (m_dma_req_buf),
		.m_dma_req_beats(m_dma_req_beats),
		.m_dma_done     (m_dma_done),
		.m_dma_error    (m_dma_error),
		.irq            (irq)
	);

endmodule
